# Generated by Django 4.0.4 on 2022-04-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hours',
            field=models.PositiveSmallIntegerField(default=''),
        ),
    ]
